FROM node:16-alpine as base

WORKDIR /usr/app

RUN apk update

COPY package*.json ./


FROM base AS dependencies

RUN npm install -g npm@8.3.2

RUN npm set progress=false && npm config set depth 0
RUN npm ci --silent


FROM base AS file-copy

COPY --from=dependencies /usr/app/node_modules ./node_modules
COPY . .


FROM base AS release

WORKDIR /usr/app

COPY --from=file-copy /usr/app ./

ENV NODE_ENV=development
ENV PORT=8080
EXPOSE 8080

ENTRYPOINT [ "npm", "run" ]
CMD [ "dev" ]
